apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jeromedevops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: DevOps
    spec:
      containers:
      - name: pleungtestapp
        image: docker.io/pleungdev/jeromedevops:$BUILD_ID
        ports:
        - containerPort: 16824
---
apiVersion: v1
kind: Service
metadata:
  name: jeromedevops
spec:
  type: LoadBalancer
  ports:
  - port: 30080
  selector:
    app: jeromedevops
