apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jeromedevops1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: jeromedevops1
    spec:
      containers:
      - name: jeromedevops
        image: docker.io/pleungdev/jeromedevops:$BUILD_ID
        ports:
        - containerPort: 16824
---
apiVersion: v1
kind: Service
metadata:
  name: jeromedevops1
spec:
  type: LoadBalancer
  ports:
  - port: 16824
  selector:
    app: jeromedevops1
